config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root "home#index"

  resources :users do
    resources :posts
  end

  resources :posts do
    resources :comments
  end
end

#                   Prefix Verb   URI Pattern                                 Controller#Action
#               home_index GET    /home/index(.:format)                       home#index
#         new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                    devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
#            user_password POST   /users/password(.:format)                   devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)               devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
#                          PATCH  /users/password(.:format)                   devise/passwords#update
#                          PUT    /users/password(.:format)                   devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                     devise/registrations#cancel
#        user_registration POST   /users(.:format)                            devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                    devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                       devise/registrations#edit
#                          PATCH  /users(.:format)                            devise/registrations#update
#                          PUT    /users(.:format)                            devise/registrations#update
#                          DELETE /users(.:format)                            devise/registrations#destroy
#                     root GET    /                                           home#index
#               user_posts GET    /users/:user_id/posts(.:format)             posts#index
#                          POST   /users/:user_id/posts(.:format)             posts#create
#            new_user_post GET    /users/:user_id/posts/new(.:format)         posts#new
#           edit_user_post GET    /users/:user_id/posts/:id/edit(.:format)    posts#edit
#                user_post GET    /users/:user_id/posts/:id(.:format)         posts#show
#                          PATCH  /users/:user_id/posts/:id(.:format)         posts#update
#                          PUT    /users/:user_id/posts/:id(.:format)         posts#update
#                          DELETE /users/:user_id/posts/:id(.:format)         posts#destroy
#                    users GET    /users(.:format)                            users#index
#                          POST   /users(.:format)                            users#create
#                 new_user GET    /users/new(.:format)                        users#new
#                edit_user GET    /users/:id/edit(.:format)                   users#edit
#                     user GET    /users/:id(.:format)                        users#show
#                          PATCH  /users/:id(.:format)                        users#update
#                          PUT    /users/:id(.:format)                        users#update
#                          DELETE /users/:id(.:format)                        users#destroy
#            post_comments GET    /posts/:post_id/comments(.:format)          comments#index
#                          POST   /posts/:post_id/comments(.:format)          comments#create
#         new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
#        edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
#             post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
#                          PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
#                          PUT    /posts/:post_id/comments/:id(.:format)      comments#update
#                          DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
#                    posts GET    /posts(.:format)                            posts#index
#                          POST   /posts(.:format)                            posts#create
#                 new_post GET    /posts/new(.:format)                        posts#new
#                edit_post GET    /posts/:id/edit(.:format)                   posts#edit
#                     post GET    /posts/:id(.:format)                        posts#show
#                          PATCH  /posts/:id(.:format)                        posts#update
#                          PUT    /posts/:id(.:format)                        posts#update
#                          DELETE /posts/:id(.:format)                        posts#destroy

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #setting the user before each of these routes to eliminate redundancy in my code
  before_action :set_user, only: [:new, :create, :show, :destroy]   
  #same as above, but only need it for show page and delete route                
  before_action :set_post, only: [:show, :destroy]                                  

  def show
    #i 'puts' a LOT of things. always be testing and making sure you know where your data changes.
    # puts "=========="
    # puts @post.id
    # puts "=========="
    @comments = Comment.where("post_id": @post.id)
    # puts "==========="
    # puts @comments
    # puts @comments.class
    # puts "============"
  end

  def new
    # puts "====="
    # p params
    # puts "======"
    #create a new instance of the Post class, which the user will populate in the form.
    @post = Post.new          
  end

  def create 
    # puts "========"
    # puts post_params
    # puts "========"
    #making a new instance of the Post class, using the post-params from the form (there's a method for that in the private methods)
    @post = Post.new(post_params)         
     if @post.save
      #push the post into the user which is set
      @user.posts << @post                
      redirect_to @user
    else
      #so if there's an issue with the form and it can't submit, this error message will post. 
      flash[:error] = "something went wrong :("                                   
      render :action => :new
    end
  end

  def destroy
    # puts "========="
    # puts "i'm here!"
    # print @post
    # puts "========="
    #set the post in the set_post method and then get rid of it!! d e s t r o y.
    @post.destroy                           
    redirect_to @user
  end

  private 
  def set_user
    #use the params to find the user
    @user = User.find(params[:user_id])
  end

  def set_post
    #same as above, but this time with post
    @post = Post.find(params[:id])          
  end

  def post_params 
    #get the params out of the form (permit only the image and caption, so other info can't be passed into the form) 
    params.require(:post).permit(:title, :content) 
  end  
end

app/views/posts/_form.html.erb
<div id = "form-container">
  <%=link_to "back to home", user_path(@user.id), :class => "label"%>
  <br>
  <br>
  <%= form_for [@user, @post] do |form| %>
    <label class = "label" for="post_title">title</label>
    <br>
    <%= form.text_field :title, :class => "input title-input" %><br><br>
    <label class = "label" for="post_content">content</label>
    <br>
    <%= form.text_area :content, :class => "content-input" %> <br><br>
    <%= form.submit :class => "button" %>
  <% end %>
</div>

app/views/posts/new.html.erb
<p id = "error-message"><%= flash[:error] %></p>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<div id = "show-container">
  <%=link_to "back to all posts", root_path, :class => "label" %>
  <br>
  <h2 class ="show-post-title"><%= @post.title %></h2>
  <p class = "caption"> by: <%= @user.email %></p>
  <p class = "caption"><%= @post.content %></p>
<% if user_signed_in? %>
  <% if @user.id == current_user.id %>
    <%=link_to '-', user_post_path(@user, @post), :method => 'delete', :class => "delete-button"%>
  <% end %>
<% end %>

<h3 class = "comments-title">comments</h3>

<% if @comments.class == Comment::ActiveRecord_Relation %>
  <% @comments.each do |comment| %>
  <div>
    <% if user_signed_in? %>
      <% if comment.author === current_user.email%>
        <%=link_to 'x', post_comment_path(:id => comment.id, :post_id => @post.id, :user_id => @user.id), :method => 'delete', :class => "delete-button comment-delete"%>
      <% end %>
    <% end %>
    <p class ="comment-content"><strong><%=comment.author%>:</strong> <%=comment.content%></p>
  </div>
<% end %>
<% elsif @comments.class == Comment %>
  <div id = "comments">
    <% if user_signed_in? %>
      <% if comment.author === current_user.email%>
        <%=link_to 'x', post_comment_path(:id => comment.id, :post_id => @post.id, :user_id => @user.id), :method => 'delete', :class => "delete-button comment-delete"%>
      <% end %>
    <% end %>
    <p class ="comment-content"><%=comment.author%>: <%=comment.content%></p>
  </div>
<% else %>
  <p> this post has no comments! </p>
<% end %>

<% if user_signed_in? %>
<p class = "message"><%= link_to 'add a comment', new_post_comment_path(:post_id => @post.id, :user_id => @user.id)%></p>
<% else %>
<p class = "message">please log in to leave a comment</p>
<% end %>
</div>

</div>